name: Push Docker Image

on:
  workflow_dispatch: # This event triggers the workflow manually

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t my-docker-image .

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          push: true
          tags: gvolarevic/gh-actions-playground:latest


